# Repository settings for Lock & Key

name: PACKAGE_NAME
description: "DESCRIPTION"
homepage: "https://thewintershadow.github.io/PACKAGE_NAME/"
topics:
  - python

# Documentation
wiki: false
pages: true

# Issues and discussions  
issues: true
discussions: false

# Security
security_and_analysis:
  secret_scanning:
    status: enabled
  secret_scanning_push_protection:
    status: enabled
